# Release Workflow for artagon-bom (Gradle)
# Triggered on version tags to release to Maven Central

name: Release to Maven Central

on:
  push:
    tags:
      - 'v*'
      - 'bom-v*'

jobs:
  release:
    name: Release to Maven Central
    uses: artagon/artagon-workflows/.github/workflows/gradle_release.yml@main
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    with:
      java-version: '25'
      verify-wrapper: true
      generate-sbom: true         # Enable SBOM for releases
      validate-sbom: true
      convert-to-spdx: true
      sign-sbom: true             # Enable Sigstore signing
      create-github-release: true
      publish-artifacts: true
    secrets: inherit
