# Release Workflow for artagon-bom
# Triggered on version tags to release to Maven Central

name: Release to Maven Central

on:
  push:
    tags:
      - 'v*'
      - 'bom-v*'

jobs:
  security-scan:
    name: Security Vulnerability Scan
    uses: artagon/artagon-workflows/.github/workflows/maven_security_scan.yml@main
    with:
      java-version: '25'
      run-dependency-check: true
      run-ossindex-audit: true
      run-trivy-scan: true
      fail-on-severity: 'HIGH'

  release:
    name: Release to Maven Central
    needs: security-scan
    uses: artagon/artagon-workflows/.github/workflows/maven-central-release.yml@main
    with:
      java-version: '25'
      maven-profile: 'ossrh-deploy'
      create-github-release: true
    secrets:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
