# Release Workflow for artagon-bom (Gradle)
# Triggered on version tags to release to Maven Central

name: Release to Maven Central

on:
  push:
    tags:
      - 'v*'
      - 'bom-v*'

jobs:
  release:
    name: Build, Sign, and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up JDK 25
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@d156388eb19639ec20ade50009f3d199ce1e2808

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808
        with:
          cache-read-only: false

      - name: Build and generate SBOM
        run: ./gradlew clean build cyclonedxBom --no-daemon -Dorg.gradle.dependency.verification=off

      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./gradlew publish --no-daemon -Dorg.gradle.dependency.verification=off

      - name: Install Cosign
        uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da

      - name: Sign SBOM with Sigstore
        run: |
          cosign sign-blob --yes \
            build/reports/bom.json \
            --output-signature build/reports/bom.json.sig \
            --output-certificate build/reports/bom.json.pem

      - name: Create GitHub Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191
        with:
          files: |
            build/reports/bom.json
            build/reports/bom.xml
            build/reports/bom.json.sig
            build/reports/bom.json.pem
          generate_release_notes: true
          draft: false
