# Release Workflow for artagon-bom (Gradle)
# Triggered on version tags to release to Maven Central

name: Release to Maven Central

on:
  push:
    tags:
      - 'v*'
      - 'bom-v*'

jobs:
  release:
    name: Release to Maven Central
    uses: artagon/artagon-workflows/.github/workflows/gradle_release.yml@main
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    with:
      java-version: '25'
      verify-wrapper: true
      generate-sbom: false        # BOM projects define constraints, not dependencies
      validate-sbom: false
      convert-to-spdx: false
      sign-sbom: false
      create-github-release: true
      publish-artifacts: true
    secrets:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
