# Snapshot Deployment Workflow for artagon-bom (Gradle)
# Automatically deploys snapshots to Maven Central on pushes to main (SNAPSHOT versions only)

name: Deploy Snapshot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-version:
    name: Check if version is SNAPSHOT
    runs-on: ubuntu-latest
    outputs:
      is-snapshot: ${{ steps.version-check.outputs.is-snapshot }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Set up JDK 25
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Check version
        id: version-check
        run: |
          VERSION=$(./gradlew properties -q | grep "^version:" | awk '{print $2}')
          echo "Project version: $VERSION"
          if [[ "$VERSION" == *-SNAPSHOT ]]; then
            echo "is-snapshot=true" >> $GITHUB_OUTPUT
            echo "✓ Version is SNAPSHOT, will deploy"
          else
            echo "is-snapshot=false" >> $GITHUB_OUTPUT
            echo "✗ Version is not SNAPSHOT ($VERSION), skipping deployment"
          fi

  deploy-snapshot:
    name: Deploy Snapshot to Maven Central
    runs-on: ubuntu-latest
    needs: check-version
    if: needs.check-version.outputs.is-snapshot == 'true'
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up JDK 25
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@d156388eb19639ec20ade50009f3d199ce1e2808

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808
        with:
          cache-read-only: false

      - name: Build and generate SBOM
        run: ./gradlew clean build cyclonedxBom --no-daemon -Dorg.gradle.dependency.verification=off

      - name: Publish Snapshot to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
        run: ./gradlew publishToMavenCentral --no-daemon -Dorg.gradle.dependency.verification=off
